name: Prettier

on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    permissions:
      pull-requests:  write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        id: prettier
        run: |
          {
            echo 'PRETTIER<<EOF'
            npx prettier --check **/*.tsx 
            echo 'EOF'
          } >> "$GITHUB_ENV"
        
        
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$PRETTIER"
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}

      - name: Run Prettier but write changes
        run: npx prettier --write **/*.tsx 
        if: always()
        

      - uses: parkerbxyz/suggest-changes@v1
        if: always()
        with:
          comment: 'Please commit the suggested changes from markdownlint.'